"""Strategy signal dataclass for the Strategy SDK."""

from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from typing import Optional


@dataclass
class StrategySignal:
    """
    Signal generated by a Python strategy.

    This is converted to the platform's internal signal format
    by the runner before passing to the risk engine.
    """

    strategy_name: str
    symbol: str
    direction: str                          # "long" or "short"
    entry_price: Decimal
    stop_loss: Optional[Decimal] = None
    take_profit: Optional[Decimal] = None
    quantity: Optional[Decimal] = None      # None = use default sizing
    metadata: dict = field(default_factory=dict)
    timestamp: Optional[datetime] = None    # Set by runner if not provided

    # Quality/scoring (optional)
    score: Optional[float] = None           # 0-100
    confidence: Optional[float] = None      # 0.0-1.0
