"""create_market_data_tables

Revision ID: 7a15366e61ae
Revises: 3f535bf10cc0
Create Date: 2026-03-13 02:27:41.877455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a15366e61ae'
down_revision: Union[str, None] = '3f535bf10cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backfill_jobs',
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bars_fetched', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backfill_jobs_status', 'backfill_jobs', ['status'], unique=False)
    op.create_index('ix_backfill_jobs_symbol_timeframe_status', 'backfill_jobs', ['symbol', 'timeframe', 'status'], unique=False)
    op.create_table('dividend_announcements',
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('corporate_action_id', sa.String(length=100), nullable=False),
    sa.Column('ca_type', sa.String(length=20), nullable=False),
    sa.Column('declaration_date', sa.Date(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('payable_date', sa.Date(), nullable=False),
    sa.Column('cash_amount', sa.Numeric(), nullable=False),
    sa.Column('stock_rate', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corporate_action_id')
    )
    op.create_index('ix_dividend_announcements_ex_date', 'dividend_announcements', ['ex_date'], unique=False)
    op.create_index('ix_dividend_announcements_payable_date', 'dividend_announcements', ['payable_date'], unique=False)
    op.create_index('ix_dividend_announcements_status', 'dividend_announcements', ['status'], unique=False)
    op.create_index('ix_dividend_announcements_symbol_ex_date', 'dividend_announcements', ['symbol', 'ex_date'], unique=False)
    op.create_table('market_symbols',
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('base_asset', sa.String(length=20), nullable=True),
    sa.Column('quote_asset', sa.String(length=20), nullable=True),
    sa.Column('broker', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('options_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'market', 'broker', name='uq_market_symbols_symbol_market_broker')
    )
    op.create_index('ix_market_symbols_broker_status', 'market_symbols', ['broker', 'status'], unique=False)
    op.create_index('ix_market_symbols_market_status', 'market_symbols', ['market', 'status'], unique=False)
    op.create_table('ohlcv_bars',
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=False),
    sa.Column('high', sa.Numeric(), nullable=False),
    sa.Column('low', sa.Numeric(), nullable=False),
    sa.Column('close', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_aggregated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'ts', name='uq_ohlcv_bars_symbol_timeframe_ts')
    )
    op.create_index('ix_ohlcv_bars_symbol_timeframe_ts', 'ohlcv_bars', ['symbol', 'timeframe', 'ts'], unique=False)
    op.create_table('watchlist_entries',
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('broker', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filter_metadata_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watchlist_entries_status', 'watchlist_entries', ['status'], unique=False)
    op.create_index('ix_watchlist_entries_symbol_market_broker_status', 'watchlist_entries', ['symbol', 'market', 'broker', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_watchlist_entries_symbol_market_broker_status', table_name='watchlist_entries')
    op.drop_index('ix_watchlist_entries_status', table_name='watchlist_entries')
    op.drop_table('watchlist_entries')
    op.drop_index('ix_ohlcv_bars_symbol_timeframe_ts', table_name='ohlcv_bars')
    op.drop_table('ohlcv_bars')
    op.drop_index('ix_market_symbols_market_status', table_name='market_symbols')
    op.drop_index('ix_market_symbols_broker_status', table_name='market_symbols')
    op.drop_table('market_symbols')
    op.drop_index('ix_dividend_announcements_symbol_ex_date', table_name='dividend_announcements')
    op.drop_index('ix_dividend_announcements_status', table_name='dividend_announcements')
    op.drop_index('ix_dividend_announcements_payable_date', table_name='dividend_announcements')
    op.drop_index('ix_dividend_announcements_ex_date', table_name='dividend_announcements')
    op.drop_table('dividend_announcements')
    op.drop_index('ix_backfill_jobs_symbol_timeframe_status', table_name='backfill_jobs')
    op.drop_index('ix_backfill_jobs_status', table_name='backfill_jobs')
    op.drop_table('backfill_jobs')
    # ### end Alembic commands ###
